#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
mirror_repo="${1:-"$repo_root/../hot-skills"}"
skill_name="${2:-hot-language}"

python3 - "$repo_root" "$mirror_repo" "$skill_name" <<'PY'
from __future__ import annotations

import hashlib
import shutil
import sys
from pathlib import Path

repo_root = Path(sys.argv[1]).resolve()
mirror_repo = Path(sys.argv[2]).resolve()
skill_name = sys.argv[3]

source_dir = repo_root / "resources" / "ai" / "skills" / skill_name
dest_dir = mirror_repo / "skills" / skill_name
manifest_path = repo_root / "resources" / "ai" / "hot-skills-mirror.toml"

if not source_dir.is_dir():
    raise SystemExit(f"Missing source skill directory: {source_dir}")


def iter_files(root: Path):
    for path in sorted(root.rglob("*")):
        if path.is_file():
            yield path


def tree_hash(root: Path) -> str:
    digest = hashlib.sha256()
    for path in iter_files(root):
        rel = path.relative_to(root).as_posix()
        digest.update(rel.encode())
        digest.update(b"\0")
        digest.update(path.read_bytes())
        digest.update(b"\0")
    return digest.hexdigest()


if not mirror_repo.is_dir():
    raise SystemExit(f"Missing hot-skills mirror repository: {mirror_repo}")


if dest_dir.exists():
    shutil.rmtree(dest_dir)
shutil.copytree(
    source_dir,
    dest_dir,
    ignore=shutil.ignore_patterns("__pycache__", ".DS_Store"),
)

hash_value = tree_hash(source_dir)

manifest_path.write_text(
    "\n".join(
        [
            "# Generated by scripts/sync-ai-assets.sh. Do not hand-edit.",
            'mirror_repo = "https://github.com/hot-dev/hot-skills"',
            f'source_path = "resources/ai/skills/{skill_name}"',
            f'mirror_path = "skills/{skill_name}"',
            f'skill = "{skill_name}"',
            f'tree_hash = "{hash_value}"',
            "",
        ]
    ),
    encoding="utf-8",
)

print(f"Synced {source_dir} -> {dest_dir}")
print(f"Wrote {manifest_path.relative_to(repo_root)}")
PY
