#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
mirror_repo="${1:-"$repo_root/../hot-skills"}"
requested_skill="${2:-}"

python3 - "$repo_root" "$mirror_repo" "$requested_skill" <<'PY'
from __future__ import annotations

import hashlib
import shutil
import sys
from pathlib import Path

repo_root = Path(sys.argv[1]).resolve()
mirror_repo = Path(sys.argv[2]).resolve()
requested_skill = sys.argv[3]

skills_root = repo_root / "resources" / "ai" / "skills"
mirror_skills_root = mirror_repo / "skills"
manifest_path = repo_root / "resources" / "ai" / "hot-skills-mirror.toml"


def skill_names(root: Path) -> list[str]:
    return sorted(
        path.name
        for path in root.iterdir()
        if path.is_dir() and (path / "SKILL.md").is_file()
    )


def iter_files(root: Path):
    for path in sorted(root.rglob("*")):
        if path.is_file() and ".DS_Store" not in path.parts and "__pycache__" not in path.parts:
            yield path


def tree_hash(root: Path) -> str:
    digest = hashlib.sha256()
    for path in iter_files(root):
        rel = path.relative_to(root).as_posix()
        digest.update(rel.encode())
        digest.update(b"\0")
        digest.update(path.read_bytes())
        digest.update(b"\0")
    return digest.hexdigest()


if not skills_root.is_dir():
    raise SystemExit(f"Missing canonical skills directory: {skills_root}")
if not mirror_repo.is_dir():
    raise SystemExit(f"Missing hot-skills mirror repository: {mirror_repo}")

names = skill_names(skills_root)
if not names:
    raise SystemExit(f"No skills found under {skills_root}")
if requested_skill and requested_skill not in names:
    raise SystemExit(f"Missing source skill directory: {skills_root / requested_skill}")

targets = [requested_skill] if requested_skill else names
for name in targets:
    source_dir = skills_root / name
    dest_dir = mirror_skills_root / name
    if dest_dir.exists():
        shutil.rmtree(dest_dir)
    shutil.copytree(
        source_dir,
        dest_dir,
        ignore=shutil.ignore_patterns("__pycache__", ".DS_Store"),
    )
    print(f"Synced {source_dir} -> {dest_dir}")

lines = [
    "# Generated by scripts/sync-ai-assets.sh. Do not hand-edit.",
    'mirror_repo = "https://github.com/hot-dev/hot-skills"',
    "",
]
for name in names:
    source_dir = skills_root / name
    lines.extend(
        [
            f'[skills."{name}"]',
            f'source_path = "resources/ai/skills/{name}"',
            f'mirror_path = "skills/{name}"',
            f'tree_hash = "{tree_hash(source_dir)}"',
            "",
        ]
    )

manifest_path.write_text("\n".join(lines), encoding="utf-8")
print(f"Wrote {manifest_path.relative_to(repo_root)}")
PY
